output_path: "data/08_reporting/correlation_matrix.png"
output_path2: "data/08_reporting/correlation_matrix_by_order.png"
output_path1: "data/08_reporting/outliers_plot.png"

categorical_features: ['person_home_ownership', 'loan_grade', 'loan_intent', 'cb_person_default_on_file']
continuous_feature: person_age
hue_feature: loan_status



hist_columns:
  - person_age
  - person_income
  - loan_amnt
  - loan_int_rate
  - person_emp_length
  - cb_person_cred_hist_length

hue_column: loan_status

test_size: 0.2
random_state: 42

cat_cols: ['person_home_ownership', 'loan_intent', 'loan_grade']
stand_col: ['person_age', 'person_income','person_emp_length', 'loan_amnt','loan_int_rate', 'loan_percent_income','cb_person_cred_hist_length']



models:
  - LogisticRegression
  - LinearSVC
  - XGBClassifier
  - RandomForestClassifier
  - AdaBoostClassifier
  - KNeighborsClassifier
  - GradientBoostingClassifier

model_params:
  LogisticRegression:
    max_iter: 1000
  XGBClassifier:
    n_estimators: 350
  RandomForestClassifier:
    n_estimators: 150
  AdaBoostClassifier:
    learning_rate: 0.15
    n_estimators: 100
  KNeighborsClassifier:
    n_neighbors: 5
  GradientBoostingClassifier:
    n_estimators: 200
    learning_rate: 0.15